name: GU Phishing CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint and Test
        run: |
          echo "Running basic checks..."
          python -c "import flask; print(f'Flask version: {flask.__version__}')"
          python -c "import app"

      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t gu-phishing .

      - name: Test Docker image
        run: |
          echo "Testing Docker image..."
          docker run -d --name test-container -p 5000:5000 gu-phishing
          sleep 5
          curl -s http://localhost:5000 || echo "Container started but may not be ready"
          docker logs test-container
          docker stop test-container

  deploy-to-github:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: app/static
          branch: gh-pages
      
      # Push Docker image to GitHub Container Registry
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/gu-phishing:latest
