name: GU Phishing Awareness CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-lint-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint code
        run: |
          echo "Running flake8..."
          flake8 app/

      - name: Run tests
        run: |
          echo "Running pytest..."
          PYTHONPATH=. pytest

      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t gu-phishing .

      - name: Save Docker image as tar
        run: |
          docker save gu-phishing -o gu-phishing.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: gu-phishing.tar
