name: GU Phishing Awareness CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test-lint-package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest flake8

    - name: Lint the app
      run: |
        echo "Running flake8..."
        flake8 app/

    - name: Run tests
      run: |
        echo "Running pytest..."
        pytest tests/

    - name: Build Docker image
      run: |
        echo "Building Docker image..."
        docker build -t gu-phishing .

    - name: Save Docker image as artifact
      uses: actions/upload-artifact@v3
      with:
        name: gu-phishing-image
        path: /home/runner/work/gu-phishing-awareness-devops/gu-phishing-awareness-devops
